### ISSUE TITLE
quickcheck test suite doesn't build with text-icu 0.8

### ISSUE THREAD

**Issue by felixonmars** [composewell/unicode-transforms#81]
```
Preprocessing test suite 'quickcheck' for unicode-transforms-0.4.0..
Building test suite 'quickcheck' for unicode-transforms-0.4.0..
[1 of 2] Compiling QuickCheckUtils  ( test/QuickCheckUtils.hs, dist/build/quickcheck/quickcheck-tmp/QuickCheckUtils.dyn_o )
[2 of 2] Compiling Main             ( test/Properties.hs, dist/build/quickcheck/quickcheck-tmp/Main.dyn_o )

test/Properties.hs:20:35: error:
    Not in scope: type constructor or class ‘ICU.NormalizationMode’
    Perhaps you meant ‘T.NormalizationMode’ (imported from Data.Text.Normalize)
    Module ‘Data.Text.ICU’ does not export ‘NormalizationMode’.
   |
20 | toICUMode :: NormalizationMode -> ICU.NormalizationMode
   |                                   ^^^^^^^^^^^^^^^^^^^^^

test/Properties.hs:23:18: error:
    Not in scope: data constructor ‘ICU.NFD’
    Module ‘Data.Text.ICU’ does not export ‘NFD’.
   |
23 |        T.NFD  -> ICU.NFD
   |                  ^^^^^^^

test/Properties.hs:24:18: error:
    Not in scope: data constructor ‘ICU.NFKD’
    Module ‘Data.Text.ICU’ does not export ‘NFKD’.
   |
24 |        T.NFKD -> ICU.NFKD
   |                  ^^^^^^^^

test/Properties.hs:25:18: error:
    Not in scope: data constructor ‘ICU.NFC’
    Module ‘Data.Text.ICU’ does not export ‘NFC’.
   |
25 |        T.NFC  -> ICU.NFC
   |                  ^^^^^^^

test/Properties.hs:26:18: error:
    Not in scope: data constructor ‘ICU.NFKC’
    Module ‘Data.Text.ICU’ does not export ‘NFKC’.
   |
26 |        T.NFKC -> ICU.NFKC
   |                  ^^^^^^^^

test/Properties.hs:30:27: error:
    Not in scope: ‘ICU.normalize’
    Perhaps you meant one of these:
      ‘T.normalize’ (imported from Data.Text.Normalize),
      ‘ICU.serialize’ (imported from Data.Text.ICU)
    Module ‘Data.Text.ICU’ does not export ‘normalize’.
   |
30 |     T.normalize mode t == ICU.normalize (toICUMode mode) t
   |                           ^^^^^^^^^^^^^
```

**Comment by felixonmars** [comment]
Upstream commit about this change: https://github.com/haskell/text-icu/commit/6e803c5f02711c218215081fecbd97ba7ccf77bb
