### PR TITLE
Support text-icu 0.8.0 for quickcheck tests (fixes #81)

### LINKED ISSUE #81: quickcheck test suite doesn't build with text-icu 0.8
```
Preprocessing test suite 'quickcheck' for unicode-transforms-0.4.0..
Building test suite 'quickcheck' for unicode-transforms-0.4.0..
[1 of 2] Compiling QuickCheckUtils  ( test/QuickCheckUtils.hs, dist/build/quickcheck/quickcheck-tmp/QuickCheckUtils.dyn_o )
[2 of 2] Compiling Main             ( test/Properties.hs, dist/build/quickcheck/quickcheck-tmp/Main.dyn_o )

test/Properties.hs:20:35: error:
    Not in scope: type constructor or class ‘ICU.NormalizationMode’
    Perhaps you meant ‘T.NormalizationMode’ (imported from Data.Text.Normalize)
    Module ‘Data.Text.ICU’ does not export ‘NormalizationMode’.
   |
20 | toICUMode :: NormalizationMode -> ICU.NormalizationMode
   |                                   ^^^^^^^^^^^^^^^^^^^^^

test/Properties.hs:23:18: error:
    Not in scope: data constructor ‘ICU.NFD’
    Module ‘Data.Text.ICU’ does not export ‘NFD’.
   |
23 |        T.NFD  -> ICU.NFD
   |                  ^^^^^^^

test/Properties.hs:24:18: error:
    Not in scope: data constructor ‘ICU.NFKD’
    Module ‘Data.Text.ICU’ does not export ‘NFKD’.
   |
24 |        T.NFKD -> ICU.NFKD
   |                  ^^^^^^^^

test/Properties.hs:25:18: error:
    Not in scope: data constructor ‘ICU.NFC’
    Module ‘Data.Text.ICU’ does not export ‘NFC’.
   |
25 |        T.NFC  -> ICU.NFC
   |                  ^^^^^^^

test/Properties.hs:26:18: error:
    Not in scope: data constructor ‘ICU.NFKC’
    Module ‘Data.Text.ICU’ does not export ‘NFKC’.
   |
26 |        T.NFKC -> ICU.NFKC
   |                  ^^^^^^^^

test/Properties.hs:30:27: error:
    Not in scope: ‘ICU.normalize’
    Perhaps you meant one of these:
      ‘T.normalize’ (imported from Data.Text.Normalize),
      ‘ICU.serialize’ (imported from Data.Text.ICU)
    Module ‘Data.Text.ICU’ does not export ‘normalize’.
   |
30 |     T.normalize mode t == ICU.normalize (toICUMode mode) t
   |                           ^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by felixonmars**

### CODE REVIEW

**Comment by harendra-kumar** [comment]
Looks good. A couple of questions:

1. Have you tested if it builds with older versions of text-icu especially since the imported module has changed from Data.Text.ICU to Data.Text.ICU.Normalize for older versions.
2. Do we need to upload a release after this merge to support the newer version of text-icu?

**Comment by felixonmars** [comment]
1. The functions used are actually in Data.Text.ICU.Normalize since 13 years ago. The module was previously imported in Data.Text.ICU too though, so I made this more explicit in comparison to the new preferred Normalize2 module.
2. That would be great :)

**Comment by harendra-kumar** [comment]
Thank you @felixonmars for the fix. I think we can merge it and upload a patch release.

**Comment by adithyaov** [comment]
The solver would never pick `text-icu-0.8.0` because of `text-icu >=0.6.2.1 && <0.8` in the benchmark `bench.`

Can you please confirm the following,
```
cabal build test:quickcheck --flag has-icu
```
works in the following cases,
1. When `text-icu == 0.8.0`
2. When `text-icu == 0.7.1.0`

**Comment by felixonmars** [comment]
> Can you please confirm the following,
> 
> ```
> cabal build test:quickcheck --flag has-icu
> ```
> 
> works in the following cases,
> 
>     1. When `text-icu == 0.8.0`
> 
>     2. When `text-icu == 0.7.1.0`

Yes, I confirm that these combination works. I didn't really look into the benchmarks though.

**Comment by adithyaov** [comment]
Sorry for the delay in merging this. This completely slipped my mind and my task list. 
We still have to change the version bounds in the cabal file. I'll do that later.

Thanks, @felixonmars
